//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 10:02:26 PM CET 
//


package ietf.params.xml.ns.keyprov.pskc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for KeyDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KeyDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Secret" type="{urn:ietf:params:xml:ns:keyprov:pskc}binaryDataType" minOccurs="0"/>
 *         &lt;element name="Counter" type="{urn:ietf:params:xml:ns:keyprov:pskc}longDataType" minOccurs="0"/>
 *         &lt;element name="Time" type="{urn:ietf:params:xml:ns:keyprov:pskc}intDataType" minOccurs="0"/>
 *         &lt;element name="TimeInterval" type="{urn:ietf:params:xml:ns:keyprov:pskc}intDataType" minOccurs="0"/>
 *         &lt;element name="TimeDrift" type="{urn:ietf:params:xml:ns:keyprov:pskc}intDataType" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KeyDataType", propOrder = {
    "secret",
    "counter",
    "time",
    "timeInterval",
    "timeDrift",
    "any"
})
public class KeyDataType {

    @XmlElement(name = "Secret")
    protected BinaryDataType secret;
    @XmlElement(name = "Counter")
    protected LongDataType counter;
    @XmlElement(name = "Time")
    protected IntDataType time;
    @XmlElement(name = "TimeInterval")
    protected IntDataType timeInterval;
    @XmlElement(name = "TimeDrift")
    protected IntDataType timeDrift;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the secret property.
     * 
     * @return
     *     possible object is
     *     {@link BinaryDataType }
     *     
     */
    public BinaryDataType getSecret() {
        return secret;
    }

    /**
     * Sets the value of the secret property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinaryDataType }
     *     
     */
    public void setSecret(BinaryDataType value) {
        this.secret = value;
    }

    /**
     * Gets the value of the counter property.
     * 
     * @return
     *     possible object is
     *     {@link LongDataType }
     *     
     */
    public LongDataType getCounter() {
        return counter;
    }

    /**
     * Sets the value of the counter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongDataType }
     *     
     */
    public void setCounter(LongDataType value) {
        this.counter = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link IntDataType }
     *     
     */
    public IntDataType getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntDataType }
     *     
     */
    public void setTime(IntDataType value) {
        this.time = value;
    }

    /**
     * Gets the value of the timeInterval property.
     * 
     * @return
     *     possible object is
     *     {@link IntDataType }
     *     
     */
    public IntDataType getTimeInterval() {
        return timeInterval;
    }

    /**
     * Sets the value of the timeInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntDataType }
     *     
     */
    public void setTimeInterval(IntDataType value) {
        this.timeInterval = value;
    }

    /**
     * Gets the value of the timeDrift property.
     * 
     * @return
     *     possible object is
     *     {@link IntDataType }
     *     
     */
    public IntDataType getTimeDrift() {
        return timeDrift;
    }

    /**
     * Sets the value of the timeDrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntDataType }
     *     
     */
    public void setTimeDrift(IntDataType value) {
        this.timeDrift = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
