//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 10:02:26 PM CET 
//


package ietf.params.xml.ns.keyprov.pskc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PINUsageModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PINUsageModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Local"/>
 *     &lt;enumeration value="Prepend"/>
 *     &lt;enumeration value="Append"/>
 *     &lt;enumeration value="Algorithmic"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PINUsageModeType")
@XmlEnum
public enum PINUsageModeType {

    @XmlEnumValue("Local")
    LOCAL("Local"),
    @XmlEnumValue("Prepend")
    PREPEND("Prepend"),
    @XmlEnumValue("Append")
    APPEND("Append"),
    @XmlEnumValue("Algorithmic")
    ALGORITHMIC("Algorithmic");
    private final String value;

    PINUsageModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PINUsageModeType fromValue(String v) {
        for (PINUsageModeType c: PINUsageModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
