//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 10:02:26 PM CET 
//


package ietf.params.xml.ns.keyprov.pskc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlgorithmParametersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlgorithmParametersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Suite" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChallengeFormat" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Encoding" use="required" type="{urn:ietf:params:xml:ns:keyprov:pskc}ValueFormatType" />
 *                 &lt;attribute name="Min" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                 &lt;attribute name="Max" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                 &lt;attribute name="CheckDigits" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ResponseFormat" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Encoding" use="required" type="{urn:ietf:params:xml:ns:keyprov:pskc}ValueFormatType" />
 *                 &lt;attribute name="Length" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                 &lt;attribute name="CheckDigits" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Extensions" type="{urn:ietf:params:xml:ns:keyprov:pskc}ExtensionsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlgorithmParametersType", propOrder = {
    "suite",
    "challengeFormat",
    "responseFormat",
    "extensions"
})
public class AlgorithmParametersType {

    @XmlElement(name = "Suite")
    protected String suite;
    @XmlElement(name = "ChallengeFormat")
    protected AlgorithmParametersType.ChallengeFormat challengeFormat;
    @XmlElement(name = "ResponseFormat")
    protected AlgorithmParametersType.ResponseFormat responseFormat;
    @XmlElement(name = "Extensions")
    protected List<ExtensionsType> extensions;

    /**
     * Gets the value of the suite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuite() {
        return suite;
    }

    /**
     * Sets the value of the suite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuite(String value) {
        this.suite = value;
    }

    /**
     * Gets the value of the challengeFormat property.
     * 
     * @return
     *     possible object is
     *     {@link AlgorithmParametersType.ChallengeFormat }
     *     
     */
    public AlgorithmParametersType.ChallengeFormat getChallengeFormat() {
        return challengeFormat;
    }

    /**
     * Sets the value of the challengeFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgorithmParametersType.ChallengeFormat }
     *     
     */
    public void setChallengeFormat(AlgorithmParametersType.ChallengeFormat value) {
        this.challengeFormat = value;
    }

    /**
     * Gets the value of the responseFormat property.
     * 
     * @return
     *     possible object is
     *     {@link AlgorithmParametersType.ResponseFormat }
     *     
     */
    public AlgorithmParametersType.ResponseFormat getResponseFormat() {
        return responseFormat;
    }

    /**
     * Sets the value of the responseFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgorithmParametersType.ResponseFormat }
     *     
     */
    public void setResponseFormat(AlgorithmParametersType.ResponseFormat value) {
        this.responseFormat = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extensions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtensions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionsType }
     * 
     * 
     */
    public List<ExtensionsType> getExtensions() {
        if (extensions == null) {
            extensions = new ArrayList<ExtensionsType>();
        }
        return this.extensions;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Encoding" use="required" type="{urn:ietf:params:xml:ns:keyprov:pskc}ValueFormatType" />
     *       &lt;attribute name="Min" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *       &lt;attribute name="Max" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *       &lt;attribute name="CheckDigits" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ChallengeFormat {

        @XmlAttribute(name = "Encoding", required = true)
        protected ValueFormatType encoding;
        @XmlAttribute(name = "Min", required = true)
        @XmlSchemaType(name = "unsignedInt")
        protected long min;
        @XmlAttribute(name = "Max", required = true)
        @XmlSchemaType(name = "unsignedInt")
        protected long max;
        @XmlAttribute(name = "CheckDigits")
        protected Boolean checkDigits;

        /**
         * Gets the value of the encoding property.
         * 
         * @return
         *     possible object is
         *     {@link ValueFormatType }
         *     
         */
        public ValueFormatType getEncoding() {
            return encoding;
        }

        /**
         * Sets the value of the encoding property.
         * 
         * @param value
         *     allowed object is
         *     {@link ValueFormatType }
         *     
         */
        public void setEncoding(ValueFormatType value) {
            this.encoding = value;
        }

        /**
         * Gets the value of the min property.
         * 
         */
        public long getMin() {
            return min;
        }

        /**
         * Sets the value of the min property.
         * 
         */
        public void setMin(long value) {
            this.min = value;
        }

        /**
         * Gets the value of the max property.
         * 
         */
        public long getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         * 
         */
        public void setMax(long value) {
            this.max = value;
        }

        /**
         * Gets the value of the checkDigits property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCheckDigits() {
            if (checkDigits == null) {
                return false;
            } else {
                return checkDigits;
            }
        }

        /**
         * Sets the value of the checkDigits property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCheckDigits(Boolean value) {
            this.checkDigits = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Encoding" use="required" type="{urn:ietf:params:xml:ns:keyprov:pskc}ValueFormatType" />
     *       &lt;attribute name="Length" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *       &lt;attribute name="CheckDigits" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ResponseFormat {

        @XmlAttribute(name = "Encoding", required = true)
        protected ValueFormatType encoding;
        @XmlAttribute(name = "Length", required = true)
        @XmlSchemaType(name = "unsignedInt")
        protected long length;
        @XmlAttribute(name = "CheckDigits")
        protected Boolean checkDigits;

        /**
         * Gets the value of the encoding property.
         * 
         * @return
         *     possible object is
         *     {@link ValueFormatType }
         *     
         */
        public ValueFormatType getEncoding() {
            return encoding;
        }

        /**
         * Sets the value of the encoding property.
         * 
         * @param value
         *     allowed object is
         *     {@link ValueFormatType }
         *     
         */
        public void setEncoding(ValueFormatType value) {
            this.encoding = value;
        }

        /**
         * Gets the value of the length property.
         * 
         */
        public long getLength() {
            return length;
        }

        /**
         * Sets the value of the length property.
         * 
         */
        public void setLength(long value) {
            this.length = value;
        }

        /**
         * Gets the value of the checkDigits property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCheckDigits() {
            if (checkDigits == null) {
                return false;
            } else {
                return checkDigits;
            }
        }

        /**
         * Sets the value of the checkDigits property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCheckDigits(Boolean value) {
            this.checkDigits = value;
        }

    }

}
