//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 10:02:26 PM CET 
//


package ietf.params.xml.ns.keyprov.pskc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KeyUsageType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="KeyUsageType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OTP"/>
 *     &lt;enumeration value="CR"/>
 *     &lt;enumeration value="Encrypt"/>
 *     &lt;enumeration value="Integrity"/>
 *     &lt;enumeration value="Verify"/>
 *     &lt;enumeration value="Unlock"/>
 *     &lt;enumeration value="Decrypt"/>
 *     &lt;enumeration value="KeyWrap"/>
 *     &lt;enumeration value="Unwrap"/>
 *     &lt;enumeration value="Derive"/>
 *     &lt;enumeration value="Generate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "KeyUsageType")
@XmlEnum
public enum KeyUsageType {

    OTP("OTP"),
    CR("CR"),
    @XmlEnumValue("Encrypt")
    ENCRYPT("Encrypt"),
    @XmlEnumValue("Integrity")
    INTEGRITY("Integrity"),
    @XmlEnumValue("Verify")
    VERIFY("Verify"),
    @XmlEnumValue("Unlock")
    UNLOCK("Unlock"),
    @XmlEnumValue("Decrypt")
    DECRYPT("Decrypt"),
    @XmlEnumValue("KeyWrap")
    KEY_WRAP("KeyWrap"),
    @XmlEnumValue("Unwrap")
    UNWRAP("Unwrap"),
    @XmlEnumValue("Derive")
    DERIVE("Derive"),
    @XmlEnumValue("Generate")
    GENERATE("Generate");
    private final String value;

    KeyUsageType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static KeyUsageType fromValue(String v) {
        for (KeyUsageType c: KeyUsageType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
